config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#new'

  resource :messages, only: [:new, :create]

  match :check, to: 'emails#check', via: [:get, :post]
  match :history, to: 'emails#history', via: [:get, :post]

  resources :webhook_events, path: 'webhooks', only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email
  attr_reader :address

  def initialize(address)
    @address = address
  end

  def do_not_contact?
    unsubscribed? or has_complaints?
  end

  def events
    response = client.get("#{domain}/events", limit: 10, event: 'delivered', to: address)
    response = response.to_h!
    response['items']
  rescue Mailgun::Error
    []
  end

  def unsubscribed?
    response = client.get("#{domain}/unsubscribes/#{address}")
    response.code == 200
  rescue Mailgun::Error
    false
  end

  def has_complaints?
    response = client.get("#{domain}/complaints/#{address}")
    response.code == 200
  rescue Mailgun::Error
    false
  end

  private

  def client
    @client ||= Mailgun::Client.new
  end

  def domain
    Rails.application.secrets.mailgun_domain
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model

  attr_accessor :email, :subject, :content, :campaign

  # Validations
  validates :email, :subject, :content, presence: true

  def deliver
    params = {
      from: "no-reply@#{mailgun_domain}",
      to: email,
      subject: subject,
      html: content,
      'o:campaign' => campaign
    }

    response = mailgun_client.send_message(mailgun_domain, params)
    response.code == 200
  rescue Mailgun::Error
    false
  end

  private

  def mailgun_client
    @mailgun_client ||= Mailgun::Client.new
  end

  def mailgun_domain
    Rails.application.secrets.mailgun_domain
  end
end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  # Validations
  validates :event, :timestamp, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def check
    if request.post?
      @email = Email.new(params[:email][:address])

      if @email.present? && @email.do_not_contact?
        flash.now[:error] = 'The email is on the DO NOT CONTACT list!'
      else
        flash.now[:success] = 'The email is not on the DO NOT CONTACT list!'
      end
    end
  end

  def history
    if request.post?
      @email = Email.new(params[:email][:address])
      @history = @email.events if @email.present?
      flash.now[:alert] = 'There are no events for this email' if @history.empty?
    end
  end

  private

  def mailgun_client
    @client ||= Mailgun::Client.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid? && @message.deliver
      redirect_to root_path, notice: 'Message sent!'
    else
      flash[:alert] = "The message could not be sent, please try again!"
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:email, :subject, :content, :campaign)
  end
end

app/controllers/webhook_events_controller.rb
class WebhookEventsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @events = WebhookEvent.order(created_at: :desc).limit(10)
  end

  def create
    @webhook = WebhookEvent.new(event_params)

    if @webhook.save
      head :ok
    else
      head :bad_request
    end
  end

  private

  def event_params
    details = params.permit(:event, :timestamp, :token, :recipient)
    details[:timestamp] = Time.zone.at(details[:timestamp].to_i)
    details
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="flash-<%= key %>">
    <%= content_tag(:span, message) %>
  </div>
<% end %>

app/views/application/_header.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <%= link_to(image_tag('logo.png'), root_path, class: 'logo') %>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>

    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><%= link_to('New message', new_messages_path) %></li>
        <li class="nav-link"><%= link_to('Check email', check_path) %></li>
        <li class="nav-link"><%= link_to('Email history', history_path) %></li>
        <li class="nav-link"><%= link_to('Events log', webhook_events_path) %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Mailgun</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'header' %>
    <%= render 'flash' %>

    <section>
      <main>
        <%= yield %>
      </main>
    </section>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/messages/new.html.erb
<h1>New message</h1>
<%= simple_form_for @message do |f| %>
  <%= f.input :email, label: 'Destination email', placeholder: 'email@example.com', hint: 'Only contato@thiagobelem.net will work' %>
  <%= f.input :subject, placeholder: 'My awesome subject' %>
  <%= f.input :content, as: :text, placeholder: 'My awesome message' %>
  <%= f.input :campaign, placeholder: 'Campaign ID' %>
  <%= f.submit 'Send message' %>
<% end %>

app/views/webhook_events/index.html.erb
<h1>Events history</h1>
<p>See all the webhook events received from Mailgun</p>

<table class="table">
  <thead>
    <th>Date</th>
    <th>Event</th>
    <th>Recipient</th>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= l(event.timestamp) %></td>
        <td>Message <code><%= event.event %></code></td>
        <td><%= event.recipient %></td>
      </tr>
    <% end %>
  </tbody>
</table>